---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.red.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure that Nginx user is exist
  user: name={{nginx_user}} system=yes

- name: Delete default site
  action: file path={{nginx_default_site}} state=absent
  when: nginx_delete_default_site
  notify:
    - nginx restart

- name: Encrypt http auth passwords
  htpasswd: path={{nginx_auth_file}} name={{item.name}} password={{item.password}}
  with_items: nginx_auth_users

- name: install openssl
  apt: pkg=openssl state=latest update_cache=yes
  when: nginx_ssl

- name: generate ssl forward secrecy key
  command: openssl dhparam -out {{ nginx_ssl_forward_secrecy_key_path }} {{ nginx_ssl_forward_secrecy_key_length }} creates={{ nginx_ssl_forward_secrecy_key_path }}
  when: nginx_ssl

- name: check ssl forward secrecy key
  file: path={{ nginx_ssl_forward_secrecy_key_path }} owner=root group=root mode=0600
  when: nginx_ssl

- name: Configure nginx
  template: src=nginx.conf.j2 dest={{nginx_dir}}/nginx.conf
  notify:
    - nginx restart

- name: Ensure the sites directory is exists
  file: name={{nginx_sites_dir}} state=directory

- name: (Monit) Copy the nginx monit service file
  template:
    src: monit.nginx.conf.j2
    dest: /etc/monit/conf.d/nginx
  notify:
    - monit restart
